spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: bankx   # 👈 ESTA LÍNEA ES LA CLAVE

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

risk:
  service:
    base-url: https://apim-cardops-demo.azure-api.net/risk/mock