spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/bankx

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2


risk:
  service:
    base-url: http://localhost:8084/mock/risk
