apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  labels:
    app: transactions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-service
  template:
    metadata:
      labels:
        app: transactions-service
    spec:
      containers:
        - name: transactions-service
          image: DOCKERHUB_USERNAME/transactions-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            # Puerto (opcional, pero correcto)
            - name: SERVER_PORT
              value: "8085"

            # 🔑 PERFIL ACTIVO → PROD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # 🔐 URI DE COSMOS DB DESDE SECRET
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: cosmos-mongo-secret
                  key: mongo-uri
