apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transactions-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.sorteosc.com
      http:
        paths:
          - path: /transactions
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8085
