apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transactions-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.sorteosc.com
      http:
        paths:
          - path: /api/transactions
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8085
